#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start

newlines="\\\trewrite ^/redirect_me https://chimachike.blogspot.com permanent;"

sudo sed -i "53i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
