#!/usr/bin/env bash
# script that script that configures a new Ubuntu machine with HAproxy load balancer

apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend Local_Server
        bind *:80
        mode http
        default_backend Web_Servers
backend Web_Servers
        balance roundrobin
        mode http
        server web-01 100.25.153.251:80 check
        server web-02 35.175.126.70:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
