#!/usr/bin/env bash
# This is a bash script that displays "Best School" 10 times but for the
# 9th iteration displays "Best Shool" and then "Hi" on a new line

index=1
while [ $index -le 10 ]
do
	echo "Best School"
	if [ $index -eq 9 ]
	then
		echo "Hi"
	fi
		((index++))
done
