#!/usr/bin/env bash
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8

cp /etc/hosts /etc/hosts.bak
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
cp -f ~/hosts.bak /etc/hosts
